### ISSUE TITLE
大佬可不可以加个随机显示的API

### ISSUE THREAD

**Issue by xzyone** [Minecraft-LittleQiu/laji-bing-pic-api#4]

**Comment by tnqzh123** [comment]
你说的随机显示是指什么？
Bing 今日美图是每天固定一张的，辣鸡 Bing 今日美图 API 不会存储到本地服务器上。

**Comment by NriotHrreion** [comment]
这个是没必要的吧，可以通过daysago参数来实现

**Comment by SerinaNya** [comment]
不能这么说，api的设计之初就是为了方便，你这样一来，不是更麻烦了？
以后会安排上的 ~~（0%）~~
