### ISSUE TITLE
请求 API 时响应时间过长

### ISSUE THREAD

**Issue by NriotHrreion** [Minecraft-LittleQiu/laji-bing-pic-api#5]
获取到今日美图时延迟太高，加载时需要时间

**Comment by SerinaNya** [comment]
你是从哪个URL加载的？`https://xiao-jin.site/api/bing/` ？

**Comment by SerinaNya** [comment]
刚才去看了一下你的网站，感谢你的支持。对于你说的延迟太高的问题，
- 如果你使用的是最新版本的Bing-Api
  请将以下几行代码自行修改
  https://github.com/jinzhijie/Bing-Api/blob/a7b806ca99053de1490dca6a543991a8c4880949/index.php#L22
  https://github.com/jinzhijie/Bing-Api/blob/a7b806ca99053de1490dca6a543991a8c4880949/index.php#L25

  - 如果你的服务器在国外，那么请把**以上2行**中的`cn.bing.com`改成`global.bing.com`，这个很好理解，应该不用我多说。
- 如果你使用的版本不是最新，那么请先`git clone`，然后再进行上面的步骤

另外，这个仓库的项目地址改了，而你的博客显然没有更新。
（一个小项目，感谢你的支持qwq

**Comment by NriotHrreion** [comment]
**好的，感谢！**

**Comment by SerinaNya** [comment]
如果可以的话，建议尝试一下 [PyBingApi](https://github.com/jinzhijie/PyBingApi)，高级缓存功能可以很好地解决这一问题，经过很长时间的测试（1 个月），非常稳定

另外感谢你对我的支持！

**Comment by NriotHrreion** [comment]
OK，不过我们的虚拟主机似乎不支持python _(虚拟主机是EasyPanel 不知道能不能装)_

**Comment by SerinaNya** [comment]
噢，等你们哪天买了云服务器，别忘了我的项目
你可以 close 了
&nbsp;

Xiao_Jin



&nbsp;




------------------&nbsp;Original&nbsp;------------------

**Comment by SerinaNya** [comment]
@NriotHrreion 您的 API 还在工作吗？如果可以的话，能否更新一下？我希望使用你的 API 作为本 repo 的 DEMO

**Comment by NriotHrreion** [comment]
> @NriotHrreion 您的 API 还在工作吗？如果可以的话，能否更新一下？我希望使用你的 API 作为本 repo 的 DEMO

好啊，我先更新一下API🙂

**Comment by NriotHrreion** [comment]
> @NriotHrreion 您的 API 还在工作吗？如果可以的话，能否更新一下？我希望使用你的 API 作为本 repo 的 DEMO

API地址: [https://api.misakal.xyz/Bing-Image](https://api.misakal.xyz/Bing-Image)

**Comment by NriotHrreion** [comment]
> > @NriotHrreion 您的 API 还在工作吗？如果可以的话，能否更新一下？我希望使用你的 API 作为本 repo 的 DEMO
> 
> API地址: https://api.misakal.xyz/Bing-Image

更新完毕
